name: 'Modify settings.xml for Maven Builds'
description: 'Customize ~/.m2/settings.xml'
inputs:
  settings-file:
    description: 'path of settings.xml file to customized.'
    default: '~/.m2/settings.xml'
  repositories:
    description: 'repositories to add to settings.xml.'
  servers:
    description: 'servers to add to settings.xml.'
runs:
  using: 'composite'
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - if: inputs.repositories != ''
      run: appender.sh ${{ inputs.settings-file }} repositories '${{ inputs.repositories }}' 
      shell: bash
    - if: inputs.servers != ''
      run: appender.sh ${{ inputs.settings-file }} servers '${{ inputs.servers }}' 
      shell: bash
